"use client"

import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { CheckCircle2, Download, RefreshCw } from "lucide-react"

interface SuccessScreenProps {
  data: {
    patient?: { name: string; age: number; policyId: string }
    totalClaimed?: number
    totalApproved?: number
    approvedCount?: number
    partialCount?: number
    rejectedCount?: number
    items?: any[]
  }
  onStartNew: () => void
}

export default function SuccessScreen({ data, onStartNew }: SuccessScreenProps) {
  const patient = data?.patient || { name: "Unknown", age: 0, policyId: "N/A" }
  const totalClaimed = data?.totalClaimed || 0
  const totalApproved = data?.totalApproved || 0
  const approvedCount = data?.approvedCount || 0
  const partialCount = data?.partialCount || 0
  const rejectedCount = data?.rejectedCount || 0
  const items = data?.items || []

  const handleDownloadSummary = () => {
    // TODO: Replace with real PDF generation endpoint
    // const response = await fetch('/api/generate-summary-pdf', {
    //   method: 'POST',
    //   body: JSON.stringify({ claimId: patient.policyId, decision: data }),
    // })
    // const blob = await response.blob()
    // const url = window.URL.createObjectURL(blob)
    // window.open(url)

    // For demo: Generate a simple text summary
    const summaryText = `
CLAIMSNAP - ADJUDICATION SUMMARY
================================
Generated: ${new Date().toLocaleString()}

PATIENT INFORMATION
-------------------
Name: ${patient.name}
Age: ${patient.age} years
Policy ID: ${patient.policyId}

CLAIM SUMMARY
-------------
Total Claimed: ₹${totalClaimed.toLocaleString()}
Final Approved: ₹${totalApproved.toLocaleString()}

ITEM BREAKDOWN
--------------
✓ Approved: ${approvedCount} items
◐ Partially Approved: ${partialCount} items
✗ Rejected: ${rejectedCount} items

DETAILED ITEMS
--------------
${items
  .map(
    (item: any) =>
      `${item.item} (${item.category})
   Claimed: ₹${(item.claimed || 0).toLocaleString()} | Approved: ₹${(item.approved || 0).toLocaleString()}
   Reason: ${item.reason || "N/A"}
`,
  )
  .join("\n")}

================================
This is an automated summary generated by ClaimSnap.
For any queries, contact claims@claimsnap.demo
    `.trim()

    // Create and download text file
    const blob = new Blob([summaryText], { type: "text/plain" })
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = `ClaimSnap_Summary_${patient.policyId}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    window.URL.revokeObjectURL(url)
  }

  return (
    <div className="container mx-auto px-4 py-16">
      <div className="max-w-2xl mx-auto space-y-8">
        {/* Success Icon and Message */}
        <div className="text-center space-y-4">
          <div className="inline-flex items-center justify-center w-24 h-24 rounded-full bg-primary/10">
            <CheckCircle2 className="h-12 w-12 text-primary" />
          </div>
          <h1 className="text-3xl font-bold">Claim Adjudication Submitted</h1>
          <p className="text-muted-foreground">Your claim decision has been successfully recorded</p>
        </div>

        {/* Summary Card */}
        <Card className="p-6 space-y-6">
          <div className="text-center pb-4 border-b">
            <p className="text-sm text-muted-foreground">Final Approved Amount</p>
            <p className="text-4xl font-bold text-primary">₹{totalApproved.toLocaleString()}</p>
            <p className="text-sm text-muted-foreground mt-1">of ₹{totalClaimed.toLocaleString()} claimed</p>
          </div>

          {/* Metrics Grid */}
          <div className="grid grid-cols-3 gap-4">
            <div className="text-center p-4 bg-primary/10 rounded-lg">
              <p className="text-3xl font-bold text-primary">{approvedCount}</p>
              <p className="text-sm text-muted-foreground">Approved</p>
            </div>
            <div className="text-center p-4 bg-accent/10 rounded-lg">
              <p className="text-3xl font-bold text-accent">{partialCount}</p>
              <p className="text-sm text-muted-foreground">Partial</p>
            </div>
            <div className="text-center p-4 bg-destructive/10 rounded-lg">
              <p className="text-3xl font-bold text-destructive">{rejectedCount}</p>
              <p className="text-sm text-muted-foreground">Rejected</p>
            </div>
          </div>

          {/* Patient & Policy Info */}
          <div className="pt-4 border-t space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">Patient Name</span>
              <span className="font-medium">{patient.name}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">Policy ID</span>
              <span className="font-medium">{patient.policyId}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">Processed On</span>
              <span className="font-medium">{new Date().toLocaleDateString()}</span>
            </div>
          </div>
        </Card>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Button variant="outline" size="lg" onClick={handleDownloadSummary} className="gap-2 bg-transparent">
            <Download className="h-4 w-4" />
            Download Summary
          </Button>
          <Button size="lg" onClick={onStartNew} className="gap-2">
            <RefreshCw className="h-4 w-4" />
            Start New Claim
          </Button>
        </div>

        {/* Footer Note */}
        <p className="text-center text-xs text-muted-foreground">
          Reference ID: CLM-{Date.now().toString(36).toUpperCase()}
          <br />
          This decision has been logged for audit purposes.
        </p>
      </div>
    </div>
  )
}
